# Use the official Microsoft Dev Container image for Node.js
FROM mcr.microsoft.com/devcontainers/javascript-node:1-20-bookworm

# Set the working directory inside the container
WORKDIR /workspace

# Expose the default port for Vite React applications
EXPOSE 5173
